Update main custom.yml

diff --git a/.github/workflows/main custom.yml b/.github/workflows/main custom.yml
--- a/.github/workflows/main custom.yml
+++ b/.github/workflows/main custom.yml
@@ -40,7 +40,7 @@ jobs:
         ARGS="O=out ARCH=arm64 CC=clang LD=ld.lld AR=llvm-ar NM=llvm-nm STRIP=llvm-strip OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- LLVM=1 LLVM_IAS=1"
         
         make $ARGS ${{ github.event.inputs.defconfig }} 2>&1 | tee defconfig.log || true
-        make -j$(nproc) $ARGS 2>&1 | tee compile.log || true
+        make -j$(nproc) $ARGS 2>&1 KCFLAGS="-Wno-error" LLVM=1 | tee compile.log || true || make O=out -j1 KCFLAGS="-Wno-error" LLVM=1
 
         if [ -f out/arch/arm64/boot/Image.gz-dtb ]; then
           ZIP_NAME="Mikazuki-${{ env.BUILD_TIME }}.zip"
